local ok, front = turtle.inspect()
assert(not ok)
assert(turtle.place())
assert(turtle.turnRight())
assert(turtle.forward())
assert(turtle.turnLeft())
assert(turtle.forward())
assert(turtle.turnLeft())
local okCrop, crop = turtle.inspectDown()
assert(okCrop and crop.name == "minecraft:wheat")
assert(crop.state.age == 7)
assert(crop.tags["minecraft:crops"] == true)
assert(turtle.digDown())
